### ISSUE TITLE
Increase performance

### ISSUE THREAD

**Issue by cyril94440** [TomKnig/TOMSMorphingLabel#17]
Hi, thank you for your awesome lib.

Do you know how could we increase performance ?
When animating 2 labels simultaneously, I get a decrease in frame rate.

Thanking you in advance.

**Comment by cyril94440** [comment]
Can be closed.
Constraints were really decreasing performances A LOT !

**Comment by TomKnig** [comment]
Hi and thanks for the note. Good to know 👍

**Comment by Austinate** [comment]
@cyril94440 can you please describe what you did to increase performance? thanks
