### ISSUE TITLE
 much slower in my app than in example?

### ISSUE THREAD

**Issue by sreeji44** [TomKnig/TOMSMorphingLabel#30]
I saw that the animations are very slow on my iPhone 5 (no problems on my iPhone 7+) and then I tried out the example from the website: those animations ran smoothly as expected.

**Comment by tomknig** [comment]
Hi! I don't actively maintain the project and won't be able to dive into that problem. I would be very happy if you find a solution and provide it as pr. Otherwise, you can also have a look at [LTMorphingLabel](https://github.com/lexrus/LTMorphingLabel) which may be more performant...
